repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=79]
        files: ^pylambdarest/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--max-line-length=90]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        exclude: ^(tests/)|^(docs/)|^(sample/)
        language: system
        types: [python]
  # Deactivated for now beacause of a bug with simplejson stubs
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.982
  #   hooks:
  #     - id: mypy
