service: pylambdarest-sample
provider:
  name: aws
  runtime: python3.8
  region: eu-west-3

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /hello
  auth:
    handler: handler.auth
    events:
      - http: POST /auth
  getUser:
    handler: handler.get_user
    events:
      - http: GET /users/{user_id}
  getUsers:
    handler: handler.get_users
    events:
      - http: GET /users

package:
  exclude:
    - "./node_modules/**"

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    usePoetry: true
